CREATE TABLE IF NOT EXISTS roles (
                                     role_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                     role_name VARCHAR(50) NOT NULL,
                                     PRIMARY KEY (role_id),
                                     UNIQUE (role_name)
);

CREATE TABLE IF NOT EXISTS users (
                                     ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                     username VARCHAR(16) NOT NULL,
                                     email VARCHAR(255),
                                     password VARCHAR(255) NOT NULL,
                                     create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                     role_id INT NOT NULL,
                                     status VARCHAR(10) NOT NULL,
                                     PRIMARY KEY (ID),
                                     UNIQUE (username),
                                     UNIQUE (email),
                                     FOREIGN KEY (role_id) REFERENCES roles(role_id)
);
